language: node_js
node_js: node
os: linux
sudo: false
cache:
  yarn: true
matrix:
  fast_finish: true

script: yarn start

after_success: test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "source" && bash deploy.sh

notifications:
  email: false