language: node_js
node_js: node
os: linux
sudo: false
cache:
  yarn: true
matrix:
  fast_finish: true

jobs:
  include:
  - stage: Prepare Cache
    script: true
  - stage: Build
    script: yarn start
  - stage: Deploy
    script: test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "source" && bash deploy.sh