type: object
properties:
  createdAt:
    type: string
    readOnly: true
    format: date-time
    description: Resource creation
    example: '2013-02-20T16:00:13.609Z'

  updatedAt:
    type: string
    readOnly: true
    format: date-time
    description: Most recent resource update
    example: '2017-12-20T00:00:09.270Z'
