type: object
properties:
  errors:
    type: object
    properties:
      title:
        type: string
      detail:
        type: string
      code:
        type: string
      status:
        type: string
